# CatEssentials Configuration
# Version 0.0.1
# This plugin is compatible for Paper 1.21+
# Note:
# Don't use TABS
# Don't remive the indentations

# ========================
#       Core Settings
# ========================
core:
  debug: false
  metrics: true
  update-checker: true

# ========================
#       Join Settings
# ========================
join:
  welcome-message:
    enabled: true # Disable if you have other plugin doing the same feature
    text: "&aWelcome {player} to the server! &7(&eCatEssentials v{version}&7)"
    prefer-authme: true  # Respect AuthMe's messages if installed

# ========================
#       Hub Settings
# ========================
hub:
  enabled: true
  mode: world  # Options: [world, proxy, transfer]
  
  # For proxy/transfer mode
  server: lobby
  
  # For world mode
  world: hub
  coordinates: [0.5, 100, 0.5, 0, 0]  # x, y, z, yaw, pitch
  teleport-delay: 3  # Seconds
  safe-teleport: true  # Prevent teleporting into blocks

# ========================
#      Economy Settings
# ========================
economy:
  enabled: true
  log-transactions: false
  starting-balance: 100.0
  currency-symbol: "$"

# ========================
#      Message Settings
# ========================
messages:
  # General Messages
  no-permission: "&cYou don't have permission to use this command"
  player-not-found: "&cPlayer not found!"
  command-usage: "&6Usage&7: &a{usage}"
  
  # Hub Messages
  hub:
    disabled: "&cHub is currently disabled!"
    teleporting: "&aTeleporting to hub in &e{delay} &aseconds..."
    arrived: "&aWelcome to the hub!"
    proxy-connecting: "&aConnecting to &e{server}&a..."
    
  # Gamemode Messages
  gamemode:
    changed: "&aYour gamemode has been set to &e{gamemode}"
    changed-other: "&aSet &e{player}&a's gamemode to &e{gamemode}"
  
  # Economy Messages
  economy:
    insufficient-funds: "&cYou need &e{amount} &cto do this!"
    payment-received: "&aReceived &e{amount} &afrom &e{sender}"
